theme: just-the-docs

title: Documentation
description: UTMStack documentation.


kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

back_to_top: true
back_to_top_text: "Back to top"

callouts:
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: blue
  warning:
    title: Warning
    color: red
